#! /bin/sh
#################################
#           Autostart           #
#################################
# Deal with incorrect primary monitor first
xrandr --output DP-5 --primary

xsetroot -cursor_name left_ptr
killall sxhkd picom dunst flameshot polybar
setxkbmap -v us
sxhkd &
picom &
dunst &
/usr/lib/xdg-desktop-portal &
/usr/lib/xdg-desktop-portal-gtk &
gamemoded &
/usr/lib/polkit-kde-authentication-agent-1 &
flameshot &



#################################
#            Monitors           #
#################################
# Make an array of displays
xoutput=$(xrandr | grep ' connected' | cut -d' ' -f1)
readarray -t displays <<< "$xoutput"

# Setup workspaces
startIndex=1
for index in "${!displays[@]}"
do
    bspc monitor ${displays[index]} -d  $startIndex $((startIndex+1)) $((startIndex+2)) $((startIndex+3))
    ((startIndex=startIndex+4))
done

bspc desktop -f ^1

# setup wallpapers
for index in "${!displays[@]}"
do
    nitrogen --set-zoom-fill --random --head=$index $HOME/Pictures/Wallpapers
done

polybar -r monitor0 &
polybar -r monitor1 &
sleep 2
xdo below -t $(xdo id -n root) $(xdo id -a polybar-monitor0_DP-5)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-monitor1_HDMI-0)

gsettings set org.gnome.desktop.interface cursor-theme 'Qogir-cursors'
gsettings set org.gnome.desktop.interface gtk-theme 'Tokyonight-Dark-BL'
gsettings set org.gnome.desktop.interface icon-theme 'Tokyonight'
gsettings set org.gnome.desktop.interface font-name "Source Sans Pro 12"
gsettings set org.gnome.desktop.interface document-font-name "Source Sans Pro 12"
gsettings set org.gnome.desktop.interface monospace-font-name "JetBrainsMono Nerd Font Regular 10"
gsettings set org.gnome.desktop.interface font-antialiasing "rgba"

#################################
#            Rules              #
#################################
bspc rule --add Pavucontrol -o state=floating follow=on focus=on
bspc rule -a polybar state=floating

#################################
#             Borders           #
#################################
bspc config top_padding 38
bspc config border_width 3
bspc config window_gap 10

bspc config normal_border_color \#363945
bspc config active_border_color \#363945
bspc config focused_border_color \#9471C1

#################################
#              Misc             #
#################################
bspc config automatic_scheme longest_side
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true
