#! /bin/sh
#################################
#           Autostart           #
#################################

xsetroot -cursor_name left_ptr
setxkbmap -v us
sxhkd &
picom &
polybar &

#################################
#            Monitors           #
#################################

xoutput=$(xrandr | grep ' connected' | cut -d' ' -f1)
readarray -t displays <<< "$xoutput"
startIndex=1
for index in "${!displays[@]}"
do
    bspc monitor ${displays[index]} -d  $startIndex $((startIndex+1)) $((startIndex+2)) $((startIndex+3))
    ((startIndex=startIndex+4))
done

for index in "${!displays[@]}"
do
    nitrogen --set-zoom-fill --random --head=$index $HOME/Pictures/Wallpapers
done


#################################
#             Borders           #
#################################

bspc config border_width 3
bspc config window_gap 10

bspc config normal_border_color \#363945
bspc config active_border_color \#363945
bspc config focused_border_color \#9471C1

#################################
#              Misc             #
#################################

bspc config automatic_scheme longest_side
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true
