--List of plugins we are using actively

require 'plugins.autopairs'
require 'plugins.autosave'
require 'plugins.bufferline'
require 'plugins.colorizer'
require 'plugins.cmp'
require 'plugins.gitsigns'
require 'plugins.hlargs'
require 'plugins.indent_blankline'
require 'plugins.kommentary'
require 'plugins.nvim-tree'
require 'plugins.todo-comments'
require 'plugins.treesitter'
require 'plugins.trouble'
require 'plugins.toggleterm'
require 'plugins.telescope'
require 'plugins.gitworktree'
require 'plugins.nullls'
